'use strict';
let editorContent=structuredClone(window.SITE_CONTENT);editorContent.settings=structuredClone(window.SITE_SETTINGS);editorContent.clubData={...structuredClone(data),...(editorContent.clubData||{})};
const adminSections={activities:{name:'봉사활동·사진',fields:['category','date','title','location','description'],labels:['분류 (이달의 봉사 / 지구 봉사)','날짜','활동 제목','장소','활동 안내']},members:{name:'회원 소개',fields:['name','role','introduction'],labels:['회원 이름','직책','소개']},history:{name:'창립 역사',fields:['year','title','description'],labels:['연도','연혁 제목','내용']},businesses:{name:'회원사 소개',fields:['name','category','description','url'],labels:['회원사 이름','업종','소개','홈페이지 주소']},news:{name:'회원 경조사',fields:['date','title','description'],labels:['날짜','제목','안내']},district:{name:'부산지구 동정',fields:['date','title','description','url'],labels:['날짜','제목','안내','출처 주소']},clubs:{name:'동호회 일정·사진',fields:['group','date','title','location','description'],labels:['골프회 / 산악회','날짜','제목','장소','안내']},photos:{name:'행사사진',fields:['date','title','description'],labels:['날짜','제목','설명']},youtube:{name:'유튜브 채널',fields:['title','url'],labels:['채널 이름','유튜브 주소']},headlines:{name:'오늘의 주요뉴스 (수동 편집)',fields:['title','url','source','published_at','topic'],labels:['기사 제목','원문 주소','매체','게시 날짜','사회복지 / 심리 / AI / 노인건강']}};
function isEditing(){return sessionStorage.getItem('lions-local-editor')==='yes';}
function requireEditor(){if(!isEditing())throw Error('관리자 편집 화면을 먼저 열어 주세요.');}
function toggleEditor(open){document.body.classList.toggle('admin-unlocked',open);$('admin-controls').hidden=!open;$('admin-login').hidden=open;}
toggleEditor(isEditing());
$('admin-login').onsubmit=e=>{e.preventDefault();if($('admin-id').value.trim()==='login'&&$('admin-password').value==='1234'){sessionStorage.setItem('lions-local-editor','yes');$('admin-password').value='';toggleEditor(true);$('login-status').textContent='편집 화면을 열었습니다. 공개 반영은 파일을 내려받아 GitHub에 올려 주세요.';}else $('login-status').textContent='아이디 또는 비밀번호를 확인하세요.';};
$('admin-logout').onclick=()=>{sessionStorage.removeItem('lions-local-editor');toggleEditor(false);$('login-status').textContent='편집 화면을 닫았습니다.';};
async function persistContent(){requireEditor();editorContent.edited_at=new Date().toISOString();const database=await db();await new Promise((resolve,reject)=>{const tx=database.transaction('album','readwrite');tx.objectStore('album').put(editorContent,'site-content');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
const settingsFields={name:'name',intro:'intro',editor:'editor','news-title':'newsTitle','news-query':'newsQuery','news-mode':'newsMode',start:'weatherStart',end:'weatherEnd',city:'weatherCity'};
for(const [id,key] of Object.entries(settingsFields))$('setting-'+id).value=editorContent.settings[key]||'';
const visibility={'home-panel':'홈·날씨·뉴스','service-panel':'봉사활동','photos-panel':'행사사진','clubs-panel':'동호회','club-information':'회원·클럽 소개',welfare:'복지통계',connections:'정보 검색'};
for(const [id,name] of Object.entries(visibility)){const label=el('label',undefined,'checkbox-label'),input=el('input');input.type='checkbox';input.dataset.section=id;input.checked=editorContent.settings.visibility?.[id]!==false;label.append(input,document.createTextNode(name));$('visibility-settings').append(label);}
$('settings-form').onsubmit=async e=>{e.preventDefault();try{requireEditor();const s=structuredClone(editorContent.settings);for(const [id,key] of Object.entries(settingsFields))s[key]=$('setting-'+id).value.trim();if(!s.name)throw Error('홈페이지 이름을 입력하세요.');if(s.weatherStart>s.weatherEnd||Date.parse(s.weatherEnd)-Date.parse(s.weatherStart)>31*86400000)throw Error('날씨 기간은 시작일부터 최대 32일로 설정하세요.');const logoFile=$('setting-logo').files[0];if(logoFile){if(!['image/png','image/jpeg','image/webp'].includes(logoFile.type)||logoFile.size>5*1024*1024)throw Error('공식 로고는 PNG/JPEG/WebP, 5MB 이하로 등록하세요.');s.logo=await readImage(logoFile);}s.visibility=Object.fromEntries([...document.querySelectorAll('#visibility-settings input')].map(x=>[x.dataset.section,x.checked]));editorContent.settings=s;await persistContent();location.reload();}catch(err){$('admin-status').textContent=err.message;}};
Object.entries(adminSections).forEach(([key,s])=>{const o=el('option',s.name);o.value=key;$('content-section').append(o);});
function editableRows(){const section=$('content-section').value;return section==='headlines'?(editorContent.headlines??[]):(editorContent.clubData[section]??[]);}
function setRows(rows){const section=$('content-section').value;if(section==='headlines'){editorContent.headlines=rows;editorContent.settings.newsMode='manual';}else editorContent.clubData[section]=rows;}
function fillFields(){const section=$('content-section').value,spec=adminSections[section],selected=$('content-item').value,r=selected===''?{}:editableRows()[Number(selected)];$('content-fields').replaceChildren();spec.fields.forEach((field,i)=>{const label=el('label',spec.labels[i]);const input=el(['description','introduction'].includes(field)?'textarea':'input');input.id='edit-'+field;if(input.tagName==='INPUT'){input.type=field==='date'?'date':field==='url'?'url':'text';input.maxLength=500;}else{input.rows=3;input.maxLength=4000;}input.value=r?.[field]||'';if(['title','name','date'].includes(field))input.required=true;label.append(input);$('content-fields').append(label);});$('content-images').value='';}
function chooseContent(){const rows=editableRows(),select=$('content-item');select.replaceChildren();const o=el('option','새 항목');o.value='';select.append(o);rows.forEach((r,i)=>{const option=el('option',[r.date,r.title||r.name||r.year].filter(Boolean).join(' · '));option.value=String(i);select.append(option);});fillFields();}
$('content-section').onchange=chooseContent;$('content-item').onchange=fillFields;chooseContent();
async function mirrorRows(section,rows){if(section==='clubs'){await clubStorage('write',rows);localClubs=rows;renderClubs();}if(section==='photos'){const expanded=expandPhotos(rows);await saveAlbum(expanded);localPhotos=expanded;renderPhotos();}}
$('content-editor').onsubmit=async e=>{e.preventDefault();try{requireEditor();const section=$('content-section').value,selected=$('content-item').value,rows=structuredClone(editableRows()),r=selected===''?{}:rows[Number(selected)];for(const field of adminSections[section].fields)r[field]=$('edit-'+field).value.trim();if((r.title!==undefined&&!r.title)||(r.name!==undefined&&!r.name))throw Error('이름 또는 제목을 입력하세요.');if(r.url&&!safeURL(r.url))throw Error('원문과 채널 주소는 https:// 로 입력하세요.');const files=[...$('content-images').files];if(files.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024))throw Error('PNG/JPEG/WebP, 사진당 10MB 이하로 선택하세요.');const images=[...(r.images||[]),...await Promise.all(files.map(readImage))];if(images.length>20)throw Error('항목당 사진은 최대 20장입니다.');if(images.length)r.images=images;if(selected==='')rows.push(r);else rows[Number(selected)]=r;setRows(rows);await persistContent();await mirrorRows(section,rows);location.reload();}catch(err){$('admin-status').textContent=err.message;}};
$('content-delete').onclick=async()=>{try{requireEditor();const selected=$('content-item').value;if(selected==='')throw Error('삭제할 항목을 선택하세요.');if(!confirm('선택한 항목을 이 브라우저에서 삭제할까요?'))return;const rows=structuredClone(editableRows());rows.splice(Number(selected),1);setRows(rows);await persistContent();await mirrorRows($('content-section').value,rows);location.reload();}catch(err){$('admin-status').textContent=err.message;}};
$('content-remove-images').onclick=async()=>{try{requireEditor();const selected=$('content-item').value;if(selected==='')throw Error('사진을 비울 항목을 선택하세요.');const rows=structuredClone(editableRows());rows[Number(selected)].images=[];delete rows[Number(selected)].image;setRows(rows);await persistContent();await mirrorRows($('content-section').value,rows);location.reload();}catch(err){$('admin-status').textContent=err.message;}};
$('admin-export').onclick=async()=>{try{requireEditor();await Promise.all([clubReady,galleryReady]);editorContent.clubData.clubs=structuredClone(clubRows());editorContent.clubData.photos=structuredClone(localPhotos??publicPhotos);if(typeof window.currentStatisticsCSV==='string')editorContent.statistics_csv=window.currentStatisticsCSV;editorContent.exported_at=new Date().toISOString();const url=URL.createObjectURL(new Blob([JSON.stringify(editorContent,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('admin-status').textContent='content.json을 내려받았습니다. GitHub의 홈페이지만들기2/data/content.json을 교체하면 공개됩니다.';}catch(err){$('admin-status').textContent=err.message;}};
$('content-import').onchange=async()=>{try{requireEditor();const file=$('content-import').files[0];if(!file)return;const c=JSON.parse(await file.text());if(!c||typeof c!=='object'||Array.isArray(c)||!c.settings||!c.clubData)throw Error('이 사이트에서 내려받은 content.json을 선택하세요.');for(const key of Object.keys(adminSections)){if(key!=='headlines'&&c.clubData[key]!==undefined&&!Array.isArray(c.clubData[key]))throw Error('자료 형식을 확인하세요.');}editorContent=c;await persistContent();if(Array.isArray(c.clubData.clubs))await mirrorRows('clubs',c.clubData.clubs);if(Array.isArray(c.clubData.photos))await mirrorRows('photos',c.clubData.photos);location.reload();}catch(err){$('admin-status').textContent='가져오기 실패: '+err.message;}};
$('admin-reset').onclick=async()=>{try{requireEditor();if(!confirm('이 브라우저에 저장한 편집 내용을 모두 지우고 공개 자료로 돌아갈까요?'))return;const database=await db();await new Promise((resolve,reject)=>{const tx=database.transaction('album','readwrite');for(const key of ['site-content','clubs','photos'])tx.objectStore('album').delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});location.reload();}catch(err){$('admin-status').textContent=err.message;}};

$('csv-file').addEventListener('change',async()=>{try{requireEditor();const file=$('csv-file').files[0];if(!file)return;const text=await file.text();csvParse(text);editorContent.statistics_csv=text;await persistContent();$('import-status').textContent='통계 CSV를 이 브라우저에 저장했습니다. 전체 업데이트 파일 다운로드로 공개 반영하세요.';}catch(err){$('import-status').textContent=err.message;}});
